# Generated by Django 6.0.5 on 2026-05-24 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_notices', models.BooleanField(default=True)),
                ('notify_official_notices', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_friend_requests', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_reminders', models.BooleanField(default=True)),
                ('push_new_notices', models.BooleanField(default=True)),
                ('push_official_notices', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_friend_requests', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=False)),
                ('push_likes', models.BooleanField(default=False)),
                ('push_mentions', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('email_official_notices', models.BooleanField(default=True)),
                ('email_suspension', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notification_type', models.CharField(choices=[('notice', 'New Notice'), ('official_notice', 'Official Notice'), ('message', 'New Message'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('like', 'Like on Notice'), ('mention', 'Mention'), ('report', 'Report Update'), ('suspension', 'Account Suspension'), ('appeal', 'Appeal Update'), ('reminder', 'Notice Reminder'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_error', models.TextField(blank=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'notification_type', '-created_at'], name='notificatio_user_id_17cab8_idx')],
            },
        ),
    ]
