# Generated by Django 5.1.15 on 2026-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Official university groups (created by staff only)'),
        ),
    ]
