# Generated by Django 5.2.8 on 2025-12-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_add_priority_expiration_templates'),
        ('notices', '0009_noticereminder_noticetemplate_notice_expires_at_and_more'),
    ]

    operations = [
    ]
