# Generated by Django 6.0.5 on 2026-05-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversationmessage_reply_and_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('pray', 'Pray'), ('fire', 'Fire')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='message_attachments/thumbs/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messaging.conversationmessage'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_c_convers_0db215_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['sender'], name='messaging_c_sender__0deaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['read_at'], name='messaging_c_read_at_304265_idx'),
        ),
        migrations.AddField(
            model_name='conversationmute',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.conversationmessage'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmute',
            unique_together={('conversation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user')},
        ),
    ]
