# Generated by Django 5.2.8 on 2025-12-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_preferences_followed_departments'),
        ('users', '0004_user_followed_departments_and_more'),
    ]

    operations = [
    ]
