# Generated by Django 5.2.8 on 2025-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20251201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('vice_chancellor', 'Vice Chancellor'), ('registrar', 'Registrar'), ('business_office', 'Business Office'), ('security', 'Head of Security'), ('lecturer', 'Lecturer'), ('dean', 'Dean'), ('hod', 'Head of Department'), ('student', 'Student'), ('other', 'Other')], default='student', max_length=100),
        ),
    ]
