# Generated by Django 6.0.5 on 2026-05-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_suspension_appeal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='suspensionappeal',
            new_name='users_suspe_user_id_92e9a7_idx',
            old_name='users_suspen_user_id_8e1dc5_idx',
        ),
        migrations.RenameIndex(
            model_name='suspensionappeal',
            new_name='users_suspe_reviewe_aedb38_idx',
            old_name='users_suspen_review_4fa135_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
