# Generated by Django 6.0.5 on 2026-05-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('examination', 'Examination'), ('holiday', 'Holiday'), ('orientation', 'Orientation'), ('graduation', 'Graduation'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='academic_ac_start_d_e8e559_idx'), models.Index(fields=['category'], name='academic_ac_categor_861200_idx'), models.Index(fields=['academic_year'], name='academic_ac_academi_3301cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=150)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('project', 'Project'), ('quiz', 'Quiz'), ('other', 'Other')], default='individual', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.course')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('supplementary', 'Supplementary')], default='final', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('invigilators', models.CharField(blank=True, max_length=500)),
                ('instructions', models.TextField(blank=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.course')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academic.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academic.examtimetable')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='examtimetable',
            index=models.Index(fields=['date'], name='academic_ex_date_cfe9df_idx'),
        ),
        migrations.AddIndex(
            model_name='examtimetable',
            index=models.Index(fields=['exam_type'], name='academic_ex_exam_ty_7c6a52_idx'),
        ),
        migrations.AddIndex(
            model_name='examtimetable',
            index=models.Index(fields=['academic_year', 'semester'], name='academic_ex_academi_6515b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course', 'academic_year', 'semester')},
        ),
    ]
